### PR TITLE
Ad Markers for BasicIMASample and AdRulesIMASample

### PR DESCRIPTION
**Pull request by firekesti**
Adds sample code for setting up ad markers when adding ads manually vs using Ad Rules.

### CODE REVIEW

**Comment by pajatopmr** [comment]
Looks good to me.  Thanks for doing this.

**Comment by firekesti** [comment]
Does anything need to be updated on the docs side? gists to be made?

**Comment by pajatopmr** [comment]
No gists were used for sample apps, I'm pretty certain.  I blazed that trail for the player controls which will impact your work on name-spacing attributes in ANP.  What you might want to check is the README.md file just to be sure a pattern has not been established that you might want to follow.

**Comment by pajato1** [comment]
Nice!

**Pull request merged**
